name: skill_swap
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  get_it: ^8.2.0
  logger: ^2.6.2
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0
  retry: ^3.1.2
  fluttertoast: ^9.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  lottie: ^3.3.2
  google_fonts: ^6.3.2
  local_auth: ^3.0.0
  skeletonizer: ^2.1.0+1
  animated_read_more_text: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  build_runner: ^2.8.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/svg/on_boarding/
    - assets/svg/icons/
    - assets/logo/
    - assets/lottie/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
